"use client";

import Layout from "@components/Layout/Layout";
import EditModal from "@components/Modal/EditModal";
import LoginModal from "@components/Modal/LoginModal";
import RegisterModal from "@components/Modal/RegisterModal";
import "@styles/globals.css";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Layout>
            <Toaster />
            {children}
            <RegisterModal />
            <LoginModal />
            <EditModal />
          </Layout>
        </SessionProvider>
      </body>
    </html>
  );
}
